trigger:
  batch: true
  paths:
    include:
    - .azure/run-bal-with-container.yml
    - .azure/templates/install-ballerina.yml
    - ballerina-samples/*

pr: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: RunBallerinaSample
  steps:
  - template: templates/install-ballerina.yml
  - script: |
      set -eo pipefail
      $BAL run ballerina-samples/hello-world.bal
    displayName: 'Run Ballerina Sample'

- job: CompileBallerinaSample
  steps:
  - template: templates/install-ballerina.yml
  - script: |
      set -eo pipefail
      $BAL build ballerina-samples/hello-world.bal
      echo "Listing compiled files"
      ls -l
    displayName: 'Compile Ballerina Sample'
